# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5fb5e1f20111bf47288675581e82721f6919a9e369fa3d8e89af6d98fdf497e3871fa8c05dced3f8ebf5ece47534c89b73097eb465e279915edc08c205db44a

test:
  secret_key_base: cedaea76a3cb62a0baff7b12cd5b52a9910d230a444429b65a12fd5c2cadc04d4746a2d2276a533a97ea3ccabaa9eafb5380eac8a0c3cefaf955b1b28a992581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
